[package]
name = "rustflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.0"
itertools = "0.10"
petgraph_algos = { git = "https://github.com/ryought/petgraph_algos" }
